use_frameworks!

platform :ios, '14.0'

target 'FSNavigationBarTransition_Example' do
  pod 'FSNavigationBarTransition', :path => '../'

  pod 'RxSwift'
  pod 'RxCocoa'
  target 'FSNavigationBarTransition_Tests' do
    inherit! :search_paths

    
  end
end
